name: Build JAR

on:
    push:
        branches: [ "1.21.1" ]
    pull_request:
        branches: [ "1.21.1" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Cache Gradle dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-gradle-

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Build with Gradle
              run: ./gradlew build

            - name: Upload JAR as Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: BrewAddon
                  path: build/libs/*.jar
                  retention-days: 60
